### ISSUE TITLE
Inverse weighting is not implemented? 

### ISSUE THREAD

**Issue by alexlib** [OpenPTV/postptv#32]
The example notebook in /examples https://github.com/OpenPTV/postptv/blob/master/examples/hdf5_scene_analysis.ipynb 

apparently uses inverse weighting. but I get NotImplementedError. Looking into the file interpolation.py I do see that it's not implemented. 

https://github.com/OpenPTV/postptv/blob/master/flowtracks/interpolation.py#L703

Shall we fix the example or complete the inverse weighting implementation?

**Comment by yosefm** [comment]
It happenned when I moved from a direct call to using `set_scene()` followed by `interpolate()`. The new way saves time on repeated interpolations in the same place. 

You can implement it again by making these two calls from  `__call__()`.

**Comment by alexlib** [comment]
I suggest rather to fix the example https://github.com/OpenPTV/postptv/blob/master/examples/hdf5_scene_analysis.ipynb
 as it's not reproducible now.
