### ISSUE TITLE
numpy changed the indexing and it causes errors

### ISSUE THREAD

**Issue by alexlib** [OpenPTV/postptv#34]
I think we need to change the way we use indexing in trajectory.py 
https://github.com/OpenPTV/postptv/blob/81f27cd68f2ff70a470a892b097422622437f8d7/flowtracks/trajectory.py#L68

from 

`self.__dict__[attr][selector]`

to 

`self.__dict__[attr][np.array(selector).astype(np.int)]`

for instance `particle_pairs` fail for the call of the type: 

```
trajid = [0,1,2]
particle_pairs(original,shifted,trajids=np.array(trajid),time_points=np.zeros(3))
```

with the error 

```
/Users/alex/miniconda3/envs/postptv/lib/python2.7/site-packages/flowtracks/pairs.pyc in particle_pairs(primary_trajects, secondary_trajects, trajids, time_points)
     52         prim_in_frame_ids = np.unique(trajids[coord_locator])
     53         prim_in_frame = [t for t in prim_traj if t.trajid() in prim_in_frame_ids]
---> 54         prim_parts = take_snapshot(prim_in_frame, frame_num, schema)
     55 
     56         sec_in_frame_ixs = trajectories_in_frame(secondary_trajects, frame_num,

/Users/alex/miniconda3/envs/postptv/lib/python2.7/site-packages/flowtracks/trajectory.py in take_snapshot(trajects, frame, schema)
    305         first_frame = traj.time()[0]
    306         for prop in copy_keys:
--> 307             kwds[prop][trix] = traj.__dict__[prop](frame - first_frame)
    308         kwds['trajid'][trix] = traj.trajid()
    309 

/Users/alex/miniconda3/envs/postptv/lib/python2.7/site-packages/flowtracks/trajectory.py in getter(self, selector)
     66                 return self.__dict__[attr]
     67             else:
---> 68                 return self.__dict__[attr][selector]
     69 
     70         def setter(self, new_val, selector=None):

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

probably also in other places, e.g. 

https://github.com/OpenPTV/postptv/blob/81f27cd68f2ff70a470a892b097422622437f8d7/flowtracks/trajectory.py#L74

**Comment by alexlib** [comment]
probably also here: 

https://github.com/OpenPTV/postptv/blob/81f27cd68f2ff70a470a892b097422622437f8d7/flowtracks/trajectory.py#L266

I got the same error about the integer only indexing and could solve it by 

`np.array(frame_num - start_times[cands]).astype(np.int)`

**Comment by yosefm** [comment]
Ok. If it works then it works. Try to do any casting to int once at the beginning if you can.

**Comment by alexlib** [comment]
> Try to do any casting to int once at the beginning if you can.

I'm not sure I understand what you ask for
